### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by burkesquires** [heikkil/unix-for-biologists#1]
Hello,
The tutorial looks wonderful. I would be interesting in possibly adapting it or using it but I need to know what the license before do so. Please add a license.
Regards,
Burke Squires

**Comment by heikkil** [comment]
Good point. 

I added a license.txt file with Creative Commons Attribution-ShareAlike 4.0 International (CC BY-SA 4.0) text. I hope it is OK for you?

**Comment by burkesquires** [comment]
That is great! Thanks!
